#Criar o BD GRAACC
CREATE DATABASE IF NOT EXISTS GRAACC
 DEFAULT  CHARACTER SET = utf8;

#Acessar o BD
USE GRAACC;

#Criar tabela
CREATE TABLE IF NOT EXISTS mail_list (
  ID int(10)  NOT NULL AUTO_INCREMENT,
  EMAIL varchar(100)  NULL UNIQUE,
  NOME varchar(100)  NULL,
   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#Cria user graacc_hackaton
CREATE USER 'graacc_hackaton'@'%' IDENTIFIED 'graacc_hackaton';

#Permissoes
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'graacc_hackaton'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON GRAACC.* TO 'graacc_hackaton'@'%';
